before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HzlvhwkGd0LwLzySaPRiTx0fSLRORCxholzdm1up35vZ6cjt4gvWIzX7lcfYOvVBYMWOKyYFu4/xwxjQHuN9eAemmJbP5ka762IRHg9RpeXDHI8Sjzpwt7mlwSZkMjRS3Kw3gTroyv/LIIXPLw6l3qJExPnTGgqjQxac4leQzNbkekBpxzIy9yec8rXyRlVuRPtS7Cs1YPftZqcZ46ZrKSVah9eFz9MHk5WdI+svpiAVO3Zxdm0bB+0MQjNSiMVgYGszLUi8NL35TvnL3R6Pd0vp4SaDegzl4loit9fbWIdhzV/0pa00AeBNqHxdmaCVUXmH81ernYqee8gK1UAuEFb4CVptaSt2vdQTqV2O5cqrsffSWJKHUfDjCdmfu1t65VfB1myVR9YptVCJzd4ub0yWLvOxOaLJ2u7Z0W+y4raVU/PRVNbzKUWmFdd7/xCRJ0kUae/CeHcphSjj5K6+q1XJjNKyIlOcKYRbZ+4+GJc4DZoXw0puUoAW/xiT2RD+bNlirRYwxKsYMteZQj+R0TxZD3XPgay6YZaT9eZo6/pUoUSwRlHqR6ugBpZMJdQ8pzIZJ6ulHoR1wX7Fje7YrmXdbv5uDdZVraaxFvACE5XbRvtL+Jw93GmVdisHwdKOFcvQtpvJjDJ2Nry8f/8nXfW5szLfe+h6k1zHoz6mCrY= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
